[package]
name = "rusty-battle-snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.193", features = ["rc"] }
serde_json = { version = "1.0.108" }
index_vec = "0.1.3"
[dependencies.rocket]
version = "0.5.0"
features = ["json"]